### ISSUE TITLE
Configurable maximum storage value

### ISSUE THREAD

**Issue by noqqe** [andreimarcu/linx-server#100]
I would like to have a config option to set the maximum storage in bytes that Uploads can use up. 

```
-maxstorage 4294967296
```

Usecase: I dont want others to be able to fill up my disk. 

At the moment I created a disk quota for the user to set limits here. 

Thanks!

**Comment by andreimarcu** [comment]
Sounds like a good idea, however how would you see it implemented? 

Right now there's no way to do that in a stateless way other than computing the directory size for every upload request (could take a long time if there are many files).

Something easier to do would be to specify a percentage of the current disk device used that cannot be passed. In case it is passed, linx could refuse uploads. 

What do you think?

**Comment by noqqe** [comment]
I would rather go with a solution that only keeps track of only the files that belong to Linx-Server. Measuring the diskusage is too error prone imho and too different between operating systems (OpenBSD user speaking...). 

Before my switch to linx I was using https://github.com/mvdan/pastecat/. Which supported max storage size. On every upload or delete an internal state in memory was changed. See: https://github.com/mvdan/pastecat/blob/master/storage/stats.go#L25-L44

As this is not really stateless and being stateless is a hard requirement for you I think the only options are 

* Inspecting all files in `meta/` during every single upload
* Closing the issue as Wontfix :P

**Comment by andreimarcu** [comment]
@noqqe 
I guess you could sum up sizes in meta during start up (even though that will increase start up time), and keep count in memory, however that assumes that nothing else writes to the directory, and that if you run multiple instances distributed, you might have discrepancies. In which case you'd effectively count how much each specific instance has uploaded.

I'm not saying I'm against it, if you're interested you can submit a pull request and we can talk about details of implementation. But will leave as wontfix for now
