### ISSUE TITLE
Option for a second upload directory

### ISSUE THREAD

**Issue by ChrisHersh** [andreimarcu/linx-server#103]
Would it be possible to add an option for a second directory so we could have one directory that you need the url to access, and one that (possibly with apache or nginx auto index) shows all files uploaded to that one. 

You could currently auto index the files directory on a separate url, but this would allow you to keep them separate so you could keep one public and still upload semi-secret files without them being displayed publicly. As far as the server is concerned I don't think the second directory would have to be treated differently than the current one, other than maybe an index page not using the auto index from the web server

**Comment by andreimarcu** [comment]
I'm not sure this would fall within the scope for linx, but you could achieve it using fancy nginx configuration, or else.
