### ISSUE TITLE
Options for disable function like "API"

### ISSUE THREAD

**Issue by fanningert** [andreimarcu/linx-server#106]
Great app, but it would be great to have a feature to disable "API" functions.

**Comment by andreimarcu** [comment]
What do you mean by that? Do you mean disabling uploads altogether?

**Comment by fanningert** [comment]
* Disable link (so not every one see that the site have a API function)
* Only upload via browser <- Ok know I saw the problem, you use the same service to upload via browser a client. So forget this idea.

**Comment by andreimarcu** [comment]
If you want to add a config option to disable the API documentation you're free to send a pull request
