### ISSUE TITLE
Restrict access - noob question

### ISSUE THREAD

**Issue by Hobbabobba** [andreimarcu/linx-server#107]
Hi Andrei, 
thanks for Linx. I got it working on my Ubuntu server behind a nginx-reverseproxy.
I can access my Linx at 192.168.0.128:7733 inside of my LAN. 
The created link is https://www.mydomain.com/link/filename   and it works perfectly.
As I understand, anyone can access the GUI of my Linx installation by klicking to https://www.mydomain.com/link, right?
How can i restrict the access? I just want to use it from inside of my LAN.

**Comment by PeerRails** [comment]
Just use deny directive of nginx config
http://nginx.org/en/docs/http/ngx_http_access_module.html

```
    location / {
        fastcgi_pass 127.0.0.1:8080;
        include fastcgi_params;
        deny all; #restrict all networks
        allow 192.168.1.0/24; # allow only local IPv4 networt 192.168.1.0/24
    }

```

**Comment by Hobbabobba** [comment]
Thanks for your help! I tried it, but just got an `403 - Forbidden errormessage.`

btw. if i use 
`deny all; #restrict all networks
        allow 192.168.1.0/24; # allow only local IPv4 networt 192.168.1.0/24`
the receiver of the link (outside of my LAN) can´t access the file, right?

**Comment by andreimarcu** [comment]
Correct, you could leave it open but only allow uploads using an API key, however you wouldn't be able to upload using the web interface (that might get fixed soon).

In the meantime you could deny on /upload instead for external access
