### ISSUE TITLE
File upload doesn't work in Internet Explorer 11

### ISSUE THREAD

**Issue by culdev** [andreimarcu/linx-server#108]
When I try to upload a file in Internet Explorer 11 there's a javascript error in [upload.js](https://github.com/andreimarcu/linx-server/blob/master/static/js/upload.js#L46).
The line:
`formData.append("expires", document.getElementById("expires").selectedOptions[0].value);`
Fails with `Unable to get property '0' of undefined or null reference`.

`document.getElementById("expires").value` works in Firefox, Google Chrome and Firefox, so maybe it should be used instead of `selectedOptions`?

**Comment by andreimarcu** [comment]
Sounds good, want to send a PR?

**Comment by culdev** [comment]
I've sent a PR.

**Comment by andreimarcu** [comment]
Thanks!
