### ISSUE TITLE
Missing Templates folder

### ISSUE THREAD

**Issue by bilicio** [andreimarcu/linx-server#110]
Hi andrei!
I could compile the app and it works perfecly on my pc. but when i try to runit on another pc it gives me a message  " could not find templates folder". Maybe my compilation are not compiling the final app with all the folders inside? im using this sintax on windows "go build -v github.com\andreimarcu\linx-server". 

thank you!

**Comment by andreimarcu** [comment]
If you look at the [build script](https://github.com/andreimarcu/linx-server/blob/master/build.sh), the step after building is to embed all the static assets in the binary by using rice:
```
rice append --exec your-linx-binary.exe
```

Let me know if you run into any issues.

**Comment by bilicio** [comment]
Do you know how to use Rice in Windows? I downloaded the package but I'm no seeing any exe to do the job. Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Oct 28, 2016 at 7:19 PM -0200, "Andrei Marcu" <notifications@github.com<mailto:notifications@github.com>> wrote:


If you look at the build script<https://github.com/andreimarcu/linx-server/blob/master/build.sh>, the step after building is to embed all the static assets in the binary by using rice:

rice append --exec your-linx-binary.exe


Let me know if you run into any issues.

-

**Comment by andreimarcu** [comment]
I think something like 
```
go install github.com/GeertJohan/go.rice
go install github.com/GeertJohan/go.rice/rice
```

**Comment by bilicio** [comment]
I've done that.. But on windows rice command return nothing because won't have any exe to do the job like go have.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Oct 28, 2016 at 7:39 PM -0200, "Andrei Marcu" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think something like

go install github.com/GeertJohan/go.rice
go install github.com/GeertJohan/go.rice/rice


-

**Comment by andreimarcu** [comment]
Alternatively, you can just build it normally, and move the .exe to the linx-server folder and run it there

**Comment by bilicio** [comment]
I got it Andrei! I needed build the rice binary too and copy the rice.exe to the go folder! Thank you!! :)

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Oct 28, 2016 at 7:44 PM -0200, "Andrei Marcu" <notifications@github.com<mailto:notifications@github.com>> wrote:


Alternatively, you can just build it normally, and move the .exe to the linx-server folder and run it there

-
