### ISSUE TITLE
Automated Builds on Docker Hub 

### ISSUE THREAD

**Issue by waja** [andreimarcu/linx-server#113]
I've seen you provide a Docker [image](https://hub.docker.com/r/andreimarcu/linx-server/) on Docker Hub. Many thanks for that!

Maybe you can switch to [Automated Builds](https://docs.docker.com/docker-hub/builds/), which is less work in the end for you. You can also create a [Repository Link](https://docs.docker.com/docker-hub/builds/#/repository-links) to "golang:alpine", which is your base image, to get your image rebuild when "golang:alpine" gets updated.

Many thanks for considering and maintaining such a great project.

**Comment by andreimarcu** [comment]
Thanks for the suggestion! I'm stuck at the repository link part, I've tried "golang:alpine", "_/golang:alpine", "golang/alpine", but all say Failed to link this repository to your Automated Build.

Any ideas?

**Comment by waja** [comment]
> Thanks for the suggestion! I'm stuck at the repository link part, I've tried "golang:alpine", "_/golang:alpine", "golang/alpine", but all say Failed to link this repository to your Automated Build.

You are using the "golang" image which has the tag "alpine". Looking into the [Documentation](https://docs.docker.com/docker-hub/builds/#/repository-links) it seems that tags could not be specified. Golang images are provided in different OS-flavors via tags.

**Comment by andreimarcu** [comment]
I ended up using the "golang" one. 
Thanks for the suggestion!
