### ISSUE TITLE
Getting "Server Error" when running with Docker and using Chrome

### ISSUE THREAD

**Issue by luciano-fiandesio** [andreimarcu/linx-server#115]
I'm running linx using Docker, behind a Apache reverse proxy. 
I can access the main page no problem, but I get a "server error" when uploading a file with Chrome. **No problem** when using Firefox.

This is how I start linx:

    docker run  -p 8080:8080 -v /home/johndoe/media/meta/:/data/meta -v /home/johndoe/media/files/:/data/files linx-server

This is my Apache proxy conf:

    <VirtualHost *:80>
      ServerName share.abc.com

      ProxyRequests Off
      ProxyPass / http://0.0.0.0:8080/
      ProxyPassReverse / http://0.0.0.0:8080/

      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>

And this is the output from linx:

    2016/11/24 10:08:07 [911b775d7f55/xmor7wdKAQ-000001] Started POST "/upload" from 172.17.0.1:35936
    2016/11/24 10:08:07 [911b775d7f55/xmor7wdKAQ-000001] Returning 400 in 176.68µs

I tried to attach to the running container, but I can't find any log.

**Comment by luciano-fiandesio** [comment]
I noticed that by using Chrome, I get simply a "Server Error". When using Firefox I get the following error on the page: test.txt: `Could not upload file: open /data/meta/z2lf70yz.md: permission denied`

**Comment by andreimarcu** [comment]
Hey there,

This could be a number of things, but from the way you described I would try the following:
- Configure ```siteURL``` if you haven't already (this can be the reason for the 400 error, because we try to ensure that you can only upload if you are on the right domain.
- Use ```-realip``` especially if you're using apache

Let me know if those help

**Comment by bpr-sulli** [comment]
Hi,

I encountered the same problem and wasn't able to resolve it by setting the siteURL or -realip. I'm using nginx with the following configurations.

Dockerfile
```
FROM golang:alpine

RUN set -ex \
        && apk add --no-cache --virtual .build-deps git \
        && go get github.com/andreimarcu/linx-server \
        && apk del .build-deps

VOLUME ["/data/files", "/data/meta"]

EXPOSE 8080
USER nobody
ENTRYPOINT ["/go/bin/linx-server", "-bind=0.0.0.0:8080", "-filespath=/data/files/", "-metapath=/data/meta/"]
CMD ["-sitename=Skyraker Share", "-allowhotlink", "siteurl=https://share.skyraker.ca","-realip"]
```

And the relevant part of my nginx config:
```
server {
    listen 443 ssl;
    server_name share.skyraker.ca;
    ssl on;
    ssl_certificate /etc/letsencrypt/live/share.skyraker.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/share.skyraker.ca/privkey.pem;

    real_ip_header X-Real-IP;
    real_ip_recursive on;

    location / {
        proxy_pass http://localhost:13002;
    }
}
```
