### ISSUE TITLE
Automatically delete outdated files

### ISSUE THREAD

**Issue by xtrafrancyz** [andreimarcu/linx-server#116]
It would be great if Linx will check all the saved files and delete old files every couple of hours.

Now the files are deleted only when trying to download them.

**Comment by andreimarcu** [comment]
Yeah, we could either have a separate tool which would do that and you'd have it in a cronjob or we could try to make it a separate thread in the server (but that could introduce some issues)

**Comment by Thor77** [comment]
+1 for thread in the server (with some locking in place obviously) because adding another binary for that is not really a good idea imho

**Comment by xtrafrancyz** [comment]
Linx is a solid program so there is no need to separate it into parts. Furthermore,it is easier to synchronize the thread than the external tool.

**Comment by mutantmonkey** [comment]
The problem with running it as a thread in the server is that if you have multiple instances using the same storage backend, they will race each other, which could potentially cause issues.

**Comment by Thor77** [comment]
@mutantmonkey I don't really understand the problem with locking, it shouldn't be too hard to implement simple locking mechanisms into the backend.

**Comment by mutantmonkey** [comment]
Yeah, you're right; it shouldn't be difficult for the localfs backend. I guess I am more concerned about complexities with additional backends, but as we don't have any yet, it's probably not worth worrying about that.

**Comment by k0nsl** [comment]
Why not just a cronjob which deletes all files older than `x` number of `days`? That's what I am using right now.

**Comment by Thor77** [comment]
Because of the reasons stated above.
