### ISSUE TITLE
Uploaded mp3 file not recognized as "audio" mime type

### ISSUE THREAD

**Issue by jfburdet** [andreimarcu/linx-server#117]
When I'm uploading an mp3 file to my local setup, it get stored as "application/octet-stream" instead of "audio/mpeg"

Then, when I'm accessing the file, I don't get the nice audio widget.

I can get the widget tweaking the meta file by hand to put correct mime type.

'hope this makes sense

**Comment by mutantmonkey** [comment]
linx-server uses [a third-party library](https://bitbucket.org/taruti/mimemagic) for MIME type detection and this is an issue with that library.

I've discussed using the user-provided MIME type as a hint, but at the moment it is ignored and detected on the server side. Do you have any thoughts, @andreimarcu?

**Comment by mutantmonkey** [comment]
linx-server uses a third-party library for MIME type detection that relies on your system MIME type information (in /usr/share/mime/magic). Can you provide more information about your environment so we can reproduce this?

**Comment by jfburdet** [comment]
I'm using it on archlinux.

You'll find its /usr/share/mime/magic attached here

[magic.zip](https://github.com/andreimarcu/linx-server/files/737856/magic.zip)

**Comment by mutantmonkey** [comment]
I'm actually on Arch and I can't reproduce this. I also discussed this with @andreimarcu and it seems mimemagic actually ships generated magic information, so it shouldn't matter what platform you're using.

Would it be possible for you to provide the MP3 file so we can take a look?

**Comment by jfburdet** [comment]
Sure, here it is on my linx setup : https://drop.burdet.ch/95wsbr9i.mp3

**Comment by mutantmonkey** [comment]
Thanks, I can reproduce this with your file. We'll look into what could be causing this.
