### ISSUE TITLE
Apache "xampp" with linx

### ISSUE THREAD

**Issue by bilicio** [andreimarcu/linx-server#126]
Andrei is there any way to automatically change wherever ip like 127.0.0.1:8080 to a hostname like http://mylinxserver.com without the port? even using a vhost the port always shows up, is there any way to hide the port on URL? Thank you!

**Comment by andreimarcu** [comment]
I'm not entirely sure I understand what you're saying. Where specifically do you want to url to change?
Did you try the ```siteurl``` option? Whatever you put there will be what shows as the url for links

**Comment by bilicio** [comment]
sorry andrei, nevermind, my bad.  i need to find a nice program to redirect traffic on my computer. im running linx and xampp. Linx on 8080 and xampp on 80. Did you know any proxy program to redirect urls to specifcs servers?

**Comment by bilicio** [comment]
i gotit andrei. for anyone that wants to run apache besides linx you need to leave xampp on port 80 and linx on 8080. inside xampp you need to enable mod_proxy modules and on vhost params write the following:
<VirtualHost *:80>
  ServerName yourServerURL

  ProxyPreserveHost on
  ProxyPass / http://192.168.5.5:8080/ #linx local ip
  ProxyPassReverse / http://192.168.5.5:8080/ #linx local ip
</VirtualHost>

thank you for this amazing app!

**Comment by andreimarcu** [comment]
Awesome!
