### ISSUE TITLE
Cross Compiling

### ISSUE THREAD

**Issue by bilicio** [andreimarcu/linx-server#128]
Hey andrei,

Im trying to cross compile the linx in windows to work on raspberry too. When i compile for windows it works like a charm, then i change the GOOS=linux, GOARCH=arm,GOARM=7 to compile for raspberry pi 3.

i could generate the file but when i run on raspberry it give's me this error:
 could not load templates[Error (where: fromfile) in index.html] open index.html: file does not exist

i though it because of rice but when i compile without rice it give's me this error:
could not load templatescould not locate box "templates"

do you know why?

thank you!

**Comment by bilicio** [comment]
I got it andrei. 
Its a rice fault 
In windows i could use "rice append --exec" after compiled the go file. For linux, raspberry this doesn't work i could only use "rice embed-go" before compile, and them "build go".

thank you

**Comment by andreimarcu** [comment]
@bilicio  glad you got it all sorted out!
