### ISSUE TITLE
Allow file uploads from contents of the clipboard

### ISSUE THREAD

**Issue by NattyNarwhal** [andreimarcu/linx-server#130]
Use cases: On Windows, I can hit the PrintScreen key to take a screenshot into the clipboard, and hold with Alt to just get the window. This is pretty convenient, but it involves having to paste into an image editor to save it before I can upload it. (There's Windows+PrtSc to save as an image instead of the clipboard, but this can't be combined with Alt. I could use the snipping tool, but that's not as quick.) Other use cases include copying a selected section from an image without having to save a file, or copying an image from a page without saving. (In the latter case, it could perhaps fetch the image's URL instead though.)

It's possible to implement - sites like imgur can manage to do it, although their implementation seems buggy?

**Comment by andreimarcu** [comment]
Sounds like a good idea, and it shouldn't be too bad to implement
