### ISSUE TITLE
Uncheck randomize filename

### ISSUE THREAD

**Issue by inattendu** [andreimarcu/linx-server#133]
Hi, thank for your work. 
I'm trying to remove the "checked" attribute on the html check box in the index template.
It may be a good improvement to let configure it via args ?

Temporary tring to recompile the binary with the wanted html template but sadly I'm getting error like : could not load templatescould not locate box "templates" when i moove the binary on my server.

**Comment by andreimarcu** [comment]
Did you run the rice append command (like in the build.sh script) after that?
If not you can move the templates/ directory where you run the binary as well

**Comment by inattendu** [comment]
Hi 
I had missed the golang-rice tools and the build.sh.
thank you, everything works as expected now.
