### ISSUE TITLE
linx-cleanup -nologs doesn't suppress output to stdout

### ISSUE THREAD

**Issue by sprnza** [andreimarcu/linx-server#136]
Hi there! Thank you for the great app!
Just found out that `-nologs` option doesn't disable output to stdout. I still get;
```
[root@server]# /home/server/build/linx/linx-cleanup -filespath /home/server/cache/linx-server/files -metapath /home/server/cache/linx-server/meta -nologs
2018/02/20 16:58:33 Delete wtn4uulx.txt
```

**Comment by andreimarcu** [comment]
Yep, you're right.

Seems like an easy fix, @mutantmonkey do you wanna do it? If not I can do it

**Comment by sprnza** [comment]
Sorry for the dumb question, but how could I get on my machine running ArchLinux? Do I need to compile the whole linx-server package using `go build`?

**Comment by andreimarcu** [comment]
@sprnza You can certainly build it with go build, or you can get one of the binaries from here: https://github.com/andreimarcu/linx-server/releases

**Comment by sprnza** [comment]
@andreimarcu The binary doesn't have the fix applied.

**Comment by andreimarcu** [comment]
@sprnza You're right, I just updated them. Thanks for noticing
