### ISSUE TITLE
Upload folder?

### ISSUE THREAD

**Issue by TheChiefMeat** [andreimarcu/linx-server#142]
I'm trying to upload a folder, but it keeps removing the folders and instead simply uploading the files contained inside? Is there any way to upload the folder?

**Comment by andreimarcu** [comment]
That's by design, you can only upload files. Most people will compress
folders and upload the file.

**Comment by TheChiefMeat** [comment]
That's a shame :( I'm using h5ai for my server, and I need a simple way to upload music folders.
