### ISSUE TITLE
Storage backends support alibabacloud?

### ISSUE THREAD

**Issue by goxofy** [andreimarcu/linx-server#163]
Storage backends support alibabacloud?

**Comment by mutantmonkey** [comment]
I could see this being useful. One thing I'm concerned about is about the overhead of adding support for a lot of different backends; support for the S3 API is pretty common among different providers, whereas the Alibaba Cloud API isn't supported by any other providers that I'm aware of.

It looks like Minio has support for an Alibaba Cloud gateway, so you could try that to provide an S3 gateway and still use Alibaba Cloud for the actual storage: https://github.com/minio/minio/pull/5103
