### ISSUE TITLE
S3 Backend Help

### ISSUE THREAD

**Issue by GFYSC** [andreimarcu/linx-server#164]
I don't know how to get this working, how and where do I start?

I'm trying to use wasabisys.com that has a S3 compatable storage, but don't know how to make the linx server use the S3 Storage instead of LocalFS.

Am i wrong putting this in a config.ini?
"s3-endpoint = s3.wasabisys.com
s3-region = eu-central-1
s3-bucket = smoothupload"

Also where do I provide these:
Environment variables to provide:
AWS_ACCESS_KEY_ID -- the S3 access key
AWS_SECRET_ACCESS_KEY -- the S3 secret key

**Comment by andreimarcu** [comment]
I tried using wasabi with linx at some point and it worked well.

How are you running linx? The environment variables would go before the executable name, like ```AWS_ACCESS_KEY_ID=youraccesskey AWS_SECRET_ACCESS_KEY=yoursecretkey ./linx-server``` 

Also your endpoint should be ```https://s3.wasabisys.com```

Let me know if this helps

**Comment by GFYSC** [comment]
> I tried using wasabi with linx at some point and it worked well.
> 
> How are you running linx? The environment variables would go before the executable name, like `AWS_ACCESS_KEY_ID=youraccesskey AWS_SECRET_ACCESS_KEY=yoursecretkey ./linx-server`
> 
> Also your endpoint should be `https://s3.wasabisys.com`
> 
> Let me know if this helps

Thanks for your reply. I've gotten further it seems but still no luck with the settings done as you say the upload just says "100%" but has done nothing.

For reference I've used a config.ini and all variable directly.
I'm using Ubuntu 16.04  - Image of attempt http://prntscr.com/mnwp9t

**Comment by andreimarcu** [comment]
Just to make sure, in that screenshot it looks like your have WS_ACCESS_KEY instead of AWS_ACCESS_KEY

**Comment by GFYSC** [comment]
> Just to make sure, in that screenshot it looks like your have WS_ACCESS_KEY instead of AWS_ACCESS_KEY

Andreimarcu, thanks once again for such an amazing reply time. - that was an issue! my bad.

I'm now getting this error http://prntscr.com/mnwqna assuming this is an issue with the S3 access, you got any recommendation on the setup for Wasabi?

**Comment by andreimarcu** [comment]
I'm not sure, maybe try regenerating access and secret keys. I didn't have that issue when I tried wasabi

**Comment by GFYSC** [comment]
> I'm not sure, maybe try regenerating access and secret keys. I didn't have that issue when I tried wasabi

I can't thank you enough, it works wonderfully.
