### ISSUE TITLE
Server error when attempting to upload file

### ISSUE THREAD

**Issue by BRTPOB** [andreimarcu/linx-server#167]
I've been using Firefox to try and upload a file to two different linx-server installations, and both times I'm receiving a "Server error" whenever the file is completed uploading. One is local, so it's instant, the other is remote and so the Server error occurred after a few seconds. I don't see an actual log file to try and troubleshoot, but the service logs don't show anything with regards to what might have gone wrong.

Two questions:

1) How can I go about getting the logs to write out to a file so I can troubleshoot?
2) What information do you need from me to see if this might be a bug?

**Comment by andreimarcu** [comment]
Can you check the browser console?

Most of the time on first installs this is because the siteurl is not correctly provided

**Comment by BRTPOB** [comment]
Sure, I'll do that, but I've been able to upload other things including images and plain text.

**Comment by BRTPOB** [comment]
OK, I figured it out using the browser debugger, thank you. Turns out nginx was refusing the file because it was too big. I've since fixed my nginx config and confirmed the upload worked.
