### ISSUE TITLE
Pasting links

### ISSUE THREAD

**Issue by kebertxela** [andreimarcu/linx-server#169]
Sometimes I just have the URL for an image/mp4 handy and when I visit my linx server, I can't just paste the URL

It would be nice if I could paste links to a URL
Maybe an input box for list of links?

**Comment by andreimarcu** [comment]
I personally use a bookmarklet like this one that I click when I want to remote upload something: 

```
javascript:(function(){location.href='https://linx.example.com/upload?randomize=yes&url='+encodeURIComponent(location.href); })();
```

This assumes you have the ```-remoteuploads``` flag, with or without a ```-remoteauthfile path/to/remoteauthfile```

As for your actual question, could be something to consider.
I'm planning to introduce themes soon and I think this type of functionality would fit well client-side

**Comment by kebertxela** [comment]
I use a bookmarklet as well,  `javascript:(function(){location.href='https://linx.isthebe.st/upload?url='+location.href+'&title='+encodeURIComponent(document.title)})()`

I'm not sure I did a good job of indicating what I was hoping for- it would also be nice if I could paste a list of things to grab and click submit, like a list of three urls upload. Bonus points if you can just paste three links from the clipboard and it'll do as if you drag and dropped three photos for example

**Comment by cottongin** [comment]
> ```
> javascript:(function(){location.href='https://linx.example.com/upload?randomize=yes&url='+encodeURIComponent(location.href); })();
> ```
> This assumes you have the `-remoteuploads` flag, with or without a `-remoteauthfile path/to/remoteauthfile`

How does one use this when using the remoteauth restriction? I've tried adding `&key=mykey` to the URL but am still getting `401 Unauthorized` responses

**Comment by andreimarcu** [comment]
@cottongin I've added direct_url=yes in https://github.com/andreimarcu/linx-server/commit/7543c82473b43760a3dca7a7dee81679462e96cc
