### ISSUE TITLE
Enable default filenames by default?

### ISSUE THREAD

**Issue by BRTPOB** [andreimarcu/linx-server#172]
I might have been missing this, but I'm trying to make it so that by default when I (or someone else) upload a file, it doesn't randomize/rename the file. I didn't see anything in the wiki or open issues about how to set this behaviour by default. Am I doing something wrong or missing something blatant?

Thanks!

**Comment by andreimarcu** [comment]
You mean in the web uploader? You could probably remove the checked attribute of the input tag in the template file.

This should become easier with upcoming themes support
