### ISSUE TITLE
Reload/stop

### ISSUE THREAD

**Issue by GitHub0202** [andreimarcu/linx-server#173]
How to restart or stop the service?
Should i exec `killall linx-server-v1.2.8_linux-amd64` ?

Sorry if it is a stupid question.

**Comment by andreimarcu** [comment]
Depends on how you run it. There's a [service file](https://github.com/andreimarcu/linx-server/blob/master/linx-server.service) in the repo which you could use to install it.

You can move the linx server binary to /usr/bin/linx-server and then move the service file to /etc/systemd/system/linx-server.service and then systemctl start linx-server

**Comment by GitHub0202** [comment]
I'm not able to start the service, maybe because I tried to append the -config /path/to/config and also my server binary file is named something like "linx-server-v1.....amd64" (I also renamed it in the service file).

Is there a documentation about linx or a Community/Forum?
