### ISSUE TITLE
Attempting to disable renaming process entirely

### ISSUE THREAD

**Issue by bootldrDNB** [andreimarcu/linx-server#174]
Hey!

I've been trying to fiddle around with `upload.go` to attempt disabling renaming of files.
I have a file index in which Linx uploads my files to, so therefore I'd want the file names to be unchanged.

I've tried modifying `barePlusExt` to disable the regex and disable the trimming of spaces.
In line 255, https://github.com/andreimarcu/linx-server/blob/master/upload.go#L255, I swapped out the spaces with underscores, so I have my ideal filenames.

Here's where it gets weird: I can upload the file no problems, it also shows up in the right folder and my file index sees it. I get a 404 when trying to use the link that Linx returns, but I can still delete the uploaded file.

This is very confusing...

**Comment by andreimarcu** [comment]
You might need to add the underscore in the regex here: https://github.com/andreimarcu/linx-server/blob/master/server.go#L165

Let me know if that helps

**Comment by bootldrDNB** [comment]
I attempted to do so, within the brackets, but it didn't help. :(

**Comment by andreimarcu** [comment]
Hmm, are there any uppercase characters? Not really sure I can help much without more info

**Comment by bootldrDNB** [comment]
I'll retrace my steps for you:

Linx is running on my Ubuntu 18.04 server behind nginx, using proxy_pass.

Original filename: `21 - Camo & Krooked - Dissolve Me (feat. Klei) (Artifical Intelligence Remix).flac`
Filename when processed by Linx: `21_-_Camo_&_Krooked_-_Dissolve_Me_(feat._Klei)_(Artifical_Intelligence_Remix).flac`

When I press the delete button after uploading to the server, the request goes through and the server responds with HTTP 200.

**Comment by andreimarcu** [comment]
Yeah that ```&``` is probably causing it

**Comment by bootldrDNB** [comment]
I can try another file with just alphanumerical characters.

**Comment by andreimarcu** [comment]
> Linx still returns a 404 when I'm trying to download the file.

But you can see the file "page"?

You changed both 	nameRe and selifRe ?

Did uploading and downloading work before you changed it to support the filenames?

**Comment by bootldrDNB** [comment]
I get the "Oops! You found a Dead Link" image.

Uploading and downloading worked prior to changing the files,
I changed both `nameRe` and `selifRe` by adding an underscore before the closing bracket.

**Comment by andreimarcu** [comment]
Did you also add A-Z? Looking at your example with 47BC6A84 there are uppercase letters

**Comment by bootldrDNB** [comment]
I just did, re-building now.

**Comment by andreimarcu** [comment]
Yeah you'd have to add those to the regex too

**Comment by bootldrDNB** [comment]
Can I just append the characters I need or do they need to be escaped in anyway?

**Comment by andreimarcu** [comment]
You're going to want to escape parentheses and some others too, I'd check a regex reference

**Comment by bootldrDNB** [comment]
And that applies to both `nameRe` and `selifRe`, correct?

**Comment by bootldrDNB** [comment]
Alright, thanks for your help so far!

**Comment by bootldrDNB** [comment]
That worked very well, thanks for your help. +1 for custom regex!
