### ISSUE TITLE
Allow custom regex for filename

### ISSUE THREAD

**Issue by andreimarcu** [andreimarcu/linx-server#175]

**Comment by Abeardevil** [comment]
What's the goal here? Should filenames have to match this regex in order to be valid?

**Comment by andreimarcu** [comment]
Yes, basically this:
https://github.com/andreimarcu/linx-server/blob/bc599ae0188b428dd07cc9e0dc6a1ce53c44dd57/upload.go#L361

which would also imply changing the behavior here:
https://github.com/andreimarcu/linx-server/blob/bc599ae0188b428dd07cc9e0dc6a1ce53c44dd57/upload.go#L374

I think this is currently low priority and might decide whether it's something useful or not
