### ISSUE TITLE
needs a demo

### ISSUE THREAD

**Issue by simonmichael** [andreimarcu/linx-server#177]
This sounds nice - thanks!

I looked for a link anywhere that would let me try this out, but didn't find one. Consider linking to a real-world or demo instance to attract more interest.

**Comment by 132ikl** [comment]
https://linx.li

**Comment by andreimarcu** [comment]
Good idea, I'll get one up soon

**Comment by andreimarcu** [comment]
Finally done here https://github.com/andreimarcu/linx-server/commit/cf0a30f46a030859033e89006be3b96b8645886d
