### ISSUE TITLE
[feature request] Background image

### ISSUE THREAD

**Issue by chrissly90** [andreimarcu/linx-server#185]
wouldn't it be a good Idea to be able to select a Background Image instead of the standard grey?

**Comment by mutantmonkey** [comment]
I don't really like the idea of adding options to support UI changes. I think this would be best handled by custom stylesheets (which can already achieved either by mounting a volume inside the Docker container or building your own Linx binary) or potentially theme support in the future.

**Comment by chrissly90** [comment]
Thank You for clarification! :)

Am 05.08.19 um 08:15 schrieb mutantmonkey:
