### ISSUE TITLE
APK files are rennamed as ZIP when downloading them

### ISSUE THREAD

**Issue by AndreiMarcuBis** [andreimarcu/linx-server#186]
It seems that on some browser (Firefox Klar on Android for example) APK files are downloaded as ZIP files.
APK files are served as application/zip files and since there is no Content-Disposition header the browser might wrongly guess a file name based on URL and MIME type.

**Comment by andreimarcu** [comment]
Is the file uploaded including filename? Does the result have the .apk extension?

**Comment by AndreiMarcuBis** [comment]
Yes the file uploaded has the ".apk" extension and it has the ".apk" on the linx platform.
It seems that Content-Disposition is not part of HTTP/1.1 even if it's widly implemented.
If the absence of Content-Disposition, which is understandable for a strict HTTP/1.1 compliance, it would be more appropriate to serve ".apk" as "application/octet-stream", or "application/vnd.android.package-archive".

I took a look at the source code and the problem seems to come from the GenerateMetadata function. It uses the filetype.Match function that only processes file header content. Since APK is technically a ZIP with a strandard structure it would require a full ZIP inspection to certify it as an APK based on its sole content which is not going to happen.

So patching the filetype project won't be an option.
One of the solutions could be to use both the detected MIME and the given extension.

I don't think Firefox Klar is wrong by serving the file as ".zip" even if the page is ".apk". HTTP/1.1 states that its the server responsability to provide the right Content-Type for safety reason, which is relatable in this case : we are talking about application downloading.

I can patch it this way if you give me the go

**Comment by andreimarcu** [comment]
We could probably have a mapping of (extension, mime type) -> "fixed" mime type
In this case (apk, application/zip) -> application/vnd.android.package-archive

This would also work for docx, etc.
