### ISSUE TITLE
File upload UI is unintuitive

### ISSUE THREAD

**Issue by j-tai** [andreimarcu/linx-server#187]
The file upload UI is unintuitive because the file upload box is placed above the upload options (the randomize filename checkbox and file expiry menu). This means that the user will likely choose the file to upload before setting the options. However, this starts the upload immediately, before the user changed the options.

To fix this, the upload options should be placed above the upload box (similar to the 'paste' page), so that the user is encouraged to change the options before choosing the file.

**Comment by andreimarcu** [comment]
Thanks for the PR however we won't change the design right now.
Hopefully soon with support for custom themes there will be more flexibility.

**Comment by bentolor** [comment]
I can only second this. This is also exactly the reason why I asked in https://github.com/andreimarcu/linx-server/pull/159#issuecomment-568910410 for an option to disable random by default. 

I'd like to understand the rationale not to accept this MR. Aesthetics? UI stability?
