### ISSUE TITLE
Markdown lists don't show numbers/bullets

### ISSUE THREAD

**Issue by j-tai** [andreimarcu/linx-server#189]
When linx-server renders a Markdown file, the list items do not have the numbers or bullets to the left of them, i.e. their `list-style` is set to `none`.

Example:

![Screenshot_20190902_214231](https://user-images.githubusercontent.com/45131430/64144807-107a0c80-cdcb-11e9-8529-fc993534a513.png)

To reproduce, create the following paste with an "md" extension:

```markdown
Ordered list:

1. one
2. two
3. three

Unordered list:

* one
* two
* three
```

**Comment by andreimarcu** [comment]
Thanks @j-tai !
