### ISSUE TITLE
Restrict downloads with passwords

### ISSUE THREAD

**Issue by n1trux** [andreimarcu/linx-server#194]
While you don't want to include a one time secret (#184) just yet, it'd be nice if there was a possibility to restrict downloads with passwords. Currently I'm using several linx installations for several clients of mine with a .htaccess file for the nginx reverse proxy in front of them, it'd be awesome if that could be done in linx itself.

**Comment by andreimarcu** [comment]
You're talking about uploading a file along with a password that would be required to view/download said file or you mean a global password for all downloads?

I wouldn't mind adding password protection for files, though I'd have to think about if it should be just an access password versus an encryption which would make the file contents more secure
