### ISSUE TITLE
Disable Paste service

### ISSUE THREAD

**Issue by stek29** [andreimarcu/linx-server#196]
I only need linx for file sharing, and i'd like to disable paste service completely.

**Comment by andreimarcu** [comment]
The "paste service" is the same as a file upload; if you're referring to the /paste page, you could disable that easily by commenting out the following: https://github.com/andreimarcu/linx-server/blob/1d583bcb489cefa0be3774080718aae2b00f9de2/server.go#L173 
 
It wouldn't be too hard to add a config flag for this so if you want you can send a pull request over
