### ISSUE TITLE
Max Expiry Time overlaps with default options

### ISSUE THREAD

**Issue by badjman** [andreimarcu/linx-server#198]
When given a max expiry time via the config options, it can overlap with default options. For example, given 31540000 seconds, or 1 year, there will be two "1 Year" listed in the drop-down menu.

**Comment by andreimarcu** [comment]
It's actually happening: https://github.com/andreimarcu/linx-server/blob/9f6346a373dba25c4570f8e7dcb8f79f11ac964e/expiry.go#L43-L45

It looks like the value used for 1 year is 31536000
https://github.com/andreimarcu/linx-server/blob/9f6346a373dba25c4570f8e7dcb8f79f11ac964e/expiry.go#L10-L18
