### ISSUE TITLE
Linx-Access-Key vs Linx-Api-Key

### ISSUE THREAD

**Issue by thomasjsn** [andreimarcu/linx-server#200]
The API documentation page uses both headers;

Protect file with password
```
Linx-Access-Key: mysecret
```
and
```
$ curl -H "Linx-Api-Key: mysecretkey" -T myphoto.jpg http://192.168.1.135:8080/upload/  
http://192.168.1.135:8080/myphoto.jpg
```

I had to use `Linx-Api-Key`to get it to work, is `Linx-Access-Key` used for something else or is it a bug in the documentation?

**Comment by andreimarcu** [comment]
The access key is for password-protecting access to individual files whereas the api key is for protecting access to upload

**Comment by thomasjsn** [comment]
Oh, that makes sense. Thanks :)
