### ISSUE TITLE
Files are not being deleted automatically

### ISSUE THREAD

**Issue by ruimartinsptl** [andreimarcu/linx-server#216]
If I upload a file and I set a lifetime, after that time the file only is deleted if someone open again the URL.
If you say that a file only have 1 minute of life, and someone open the link 30 seconds after you create the link, and then nobody opens again the URL, the file will stay in server...
Then you think the file is deleted... But no...

**Comment by andreimarcu** [comment]
Yes, that's covered here: https://github.com/andreimarcu/linx-server#cleaning-up-expired-files
