### ISSUE TITLE
Please create an ARM image in docker hub :)

### ISSUE THREAD

**Issue by ruimartinsptl** [andreimarcu/linx-server#217]
I figured out that you only have in your Docker Hub a x64 image.

Then I created an ARM image for raspberry here:
https://hub.docker.com/r/ruimartinsptl/linx-server

But this is your code compiled to ARM with `docker buildx`, then, maybe you can offer a compiled ARM image in your Docker Hub too :)

**Comment by TheGreatestJannet** [comment]
This is why it won't start on my raspberry pi! Is there any progress on this? I assume currently if we want the latest version we have to use the binary.

**Comment by andreimarcu** [comment]
@ruimartinsptl Finally done

**Comment by TheGreatestJannet** [comment]
Thank you very much!
