### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by Abeardevil** [andreimarcu/linx-server#219]
Linx-server needs error logging like hella. I'm planning to add some, and will open a PR for your consideration when I'm done. 

Main issue here is sometimes I'll get a 400 or 500 trying to upload something and have no idea why. There are lots of places in the code where we encounter an error, but we just throw the value away. I'd like to add error logging in all those places.

**Comment by Abeardevil** [comment]
Here's an example of what I mean:

https://github.com/andreimarcu/linx-server/blob/fb0d44f132d64a7cc68fda0fd9020a4e3e4348f7/upload.go#L66

We should be logging err here.

**Comment by andreimarcu** [comment]
Sounds good!
