### ISSUE TITLE
2.3.8 release assets

### ISSUE THREAD

**Issue by Thor77** [andreimarcu/linx-server#234]
Hi,

the assets attached to the [2.3.8 release](https://github.com/andreimarcu/linx-server/releases/tag/v2.3.8) are named `${asset}-v2.3.7_...` (instead of .8), is there a reason for that?

**Comment by andreimarcu** [comment]
It's identical to 2.3.8, just a new tag to use the new multi-arch docker builds

**Comment by Thor77** [comment]
That breaks the build of my [linx-server-bin aur package](https://aur.archlinux.org/packages/linx-server-bin/), because it expects the [assets name to match the tag name](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linx-server-bin#n26) :/

**Comment by andreimarcu** [comment]
I updated the release

**Comment by Thor77** [comment]
Thanks!
