### ISSUE TITLE
basicauth with built-in http server

### ISSUE THREAD

**Issue by gbytedev** [andreimarcu/linx-server#236]
I am running this amazing app via docker using the built-in http server.

In order to restrict upload access to certain users, I understand I need to enable the options `basicauth = true` and provide the path to the authfile via `authfile = path/to/authfile`

I don't however grasp what the structure of the authfile should be. There is a mention of `linx-genkey` - how is it supposed to be run? I cannot find the binary inside of the container.

Thank you in advance!

**Comment by andreimarcu** [comment]
I don't think we include it in the container. Might look at doing that in the future. 

Right now i'd recommend building it yourself or downloading the binary in the releases (there's a separate linx-genkey binary provided for each release). 

Running that on your computer will generate a hash you put in your authfile. You can generate as many as you need and put each one on a new line in the authfile

**Comment by gbytedev** [comment]
Thank you, that was helpful.
