### ISSUE TITLE
No authentication prompt when sharing through paste functionality

### ISSUE THREAD

**Issue by wolfpld** [andreimarcu/linx-server#244]
Prerequisite for this issue is having upload authentication enabled, e.g.:

```
authfile = /etc/linx-server/authfile
basicauth = true
```

Uploading files through the main page works correctly, the authentication prompt is displayed and user can enter the password. Depending on password correctness, file is either stored, or the upload action is cancelled.

When an **authenticated** user (i.e. one that has already entered password on the main page) then goes to the /paste sub-page and tries to create a new text file, everything works correctly.

However, if an **unauthenticated** user goes to the /paste sub-page and tries to submit a new item, the server refuses the POST request with 401 error message, but the user is never presented with a password prompt. Instead, browser enters into seemingly endless waiting-for-server state, which is eventually terminated due to timeout. Then two things may happen:
- On Chrome an authentication prompt is displayed.
- Firefox shows "cannot establish a secure connection" error message.

**Comment by andreimarcu** [comment]
I can't repro this on firefox. 
Make sure you use different sessions when testing different configs
