### ISSUE TITLE
Files not saved

### ISSUE THREAD

**Issue by witchent** [andreimarcu/linx-server#247]
I set up linx-server via docker, using only one volume to bind to /data. The /data/files and /data/meta folders got created, but they stay empty even if I upload something.
I guess it uses some other path inside the image as I cannot access uploaded files after I removed and restarted the container (with the same volume)
Setting`filespath = /data/files` did not change anything either.

The logs are quiet about everything. The config file is apparently being used, as changing the sitename works. Is there anything else I can do?

**Comment by andreimarcu** [comment]
Seems like an error with your setup.

What if you mount it to somewhere else than /data, like /mydata, then change filespath and metapath in the config?

**Comment by witchent** [comment]
Still same problem. It clearly mounts to /mydata (as I had to adapt the config path as well), it reads the config (as seen by the name) but it apparently ignores some lines, for example I noticed that even if I change the port, it still listens to 8080. My hole config is this:
```
bind = 127.0.0.1:3000
sitename = Linx
siteurl = https://myDomainName/linx
selifpath = s
maxsize = 4294967296
maxexpiry = 0
allowhotlink = true
remoteuploads = true
nologs = false
force-random-filename = false
cleanup-every-minutes = 30
fastcgi = true
filespath = /mydata/files
metapath = /mydata/meta
```

Maybe something is wrong with it?

**Comment by andreimarcu** [comment]
The docker image has the following:
```
ENTRYPOINT ["/usr/local/bin/linx-server", "-bind=0.0.0.0:8080", "-filespath=/data/files/", "-metapath=/data/meta/"]
CMD ["-sitename=linx", "-allowhotlink"]
```
Therefore you probably want to either use docker compose and change them as suggested in the readme, or manually provide these in your docker run command
