### ISSUE TITLE
Using Backblaze B2 (S3 API) leak all metadata

### ISSUE THREAD

**Issue by benpro** [andreimarcu/linx-server#254]
If you use a B2 bucket, the password feature will not work and you will leak all metadata.

Example: 

```
...
< x-bz-upload-timestamp: 1606189257000
< x-bz-info-accesskey: test
< x-bz-info-size: 1819748
< x-bz-info-sha256sum: 2a7fc760ed1f2bf094474b857d8113fc07338cd63e018c950ce398caa4e9abf2
< x-bz-info-deletekey: MmyKcGH4G1zTtUJhDLYHFyKlw5g8HW
...
```

Backblaze S3 API is returning all metadata. I am not sure of the behavior of Amazon S3... But in this case storing `accesskey` and `deletekey` on B2 metadata make no sense.

**Comment by mutantmonkey** [comment]
Where is this happening exactly? Are you using a public bucket or is linx-server returning these headers?

**Comment by benpro** [comment]
In fact I set a 301 to redirect `/selif/*` to a specific other domain where is my public bucket...
So it totally makes sense that by bypassing Linx stream I don't have the password feature.
As for specific headers I will remove them.
Closing the issue as this not related to Linx.

Sorry for the noise.
