### ISSUE TITLE
Server responded with 0 code behind NGiNX reverse proxy

### ISSUE THREAD

**Issue by 12nick12** [andreimarcu/linx-server#260]
Hi, I'm running this behind NGiNX reverse proxy and am connecting via fastcgi, when trying to upload larger files I get the "Server responded with 0 code" error, but there's nothing in the NGiNX log. My server is running Debian.

**Comment by andreimarcu** [comment]
are you passing in the correct siteurl?

**Comment by 12nick12** [comment]
Would that be done via the reverse proxy?

**Comment by 12nick12** [comment]
The issue seemed to be fixed by editing the client_body_temp_path config. I think nginx was running out of disk space so by changing this it allows me to point it somewhere where there's enough space
