### ISSUE TITLE
linx-genkey

### ISSUE THREAD

**Issue by G-R-A-F-F** [andreimarcu/linx-server#261]
Hi,
How to use this tool?
I am using arm docker image and pulled 64 and regular versions on the container.
Can't make them run.

/data $ ./linx-genkey-v2.3.8_linux-arm64 
sh: ./linx-genkey-v2.3.8_linux-arm64: Permission denied
/data $ ./linx-genkey-v2.3.8_linux-arm
sh: ./linx-genkey-v2.3.8_linux-arm: Permission denied

-rwxrwxrwx    1 nobody   nobody     2141507 Aug 17 06:30 linx-genkey-v2.3.8_linux-arm
-rwxrwxrwx    1 nobody   nobody     2292046 Aug 17 06:30 linx-genkey-v2.3.8_linux-arm64

Could you please describe the process of setting up authentication?

**Comment by andreimarcu** [comment]
This looks like a permission issue?

Can you try ```chmod u+x linx-genkey*```

Or maybe chown to a user?


Alternatively, you can download the binary from https://github.com/andreimarcu/linx-server/releases and run it on your own machine, as it doesn't have to run on the same machine as linx is running.
All the tool does is generate the hashed key that you put in the auth key text file

**Comment by G-R-A-F-F** [comment]
There is something wrong with the permissions of my data folder. 
I have managed to make it work in the container in the following way:
```
/data $ cp ./linx-genkey-v2.3.8_linux-arm64 /tmp/
/data $ /tmp/linx-genkey-v2.3.8_linux-arm64 
Enter key to hash: test
oAJbxMTS9aVHu02YzCt6MHWvL4bHRvikkbLmc/Mzkbw= 
```

Thanks.
