### ISSUE TITLE
Upload via url, image rehosting.

### ISSUE THREAD

**Issue by 3291823** [andreimarcu/linx-server#264]
The ability to rehost images via posting a url would be a nice feature.
Example: rehost i.redd.it/image.png to linx-server instance.
Similar to 'catbox.moe's  upload via url option.

TIA.

**Comment by mutantmonkey** [comment]
This is already supported with the `remoteuploads` option.

**Comment by 3291823** [comment]
Oh, silly me I had this already enabled. Thanks.
