### ISSUE TITLE
Support different storage backends

### ISSUE THREAD

**Issue by andreimarcu** [andreimarcu/linx-server#28]
S3, etc..

**Comment by matthazinski** [comment]
And Tahoe-LAFS!

**Comment by mutantmonkey** [comment]
There should be encryption support for backends that don't do it automatically. I suggest AES256-GCM. Tahoe-LAFS does encryption itself so there's no need for it in that backend.

**Comment by mutantmonkey** [comment]
https://godoc.org/golang.org/x/crypto/nacl/secretbox is also available

**Comment by mutantmonkey** [comment]
One thing we may want to consider is how to store metadata. We could move to using a key-value store to both improve performance on backends with high latency as well as reduce cost for S3 or similar paid storage platforms.

**Comment by andreimarcu** [comment]
The idea would be for each storage backend to define how it stores files and metadata, so you could have a backend that is file on disk + metadata somewhere else. And S3 backends could use the metadata provided by the API already, and so on

**Comment by mutantmonkey** [comment]
The framework for this is in place with fcd18eceec5c637d9a102dc63698e270fee35103. Now people just need to write stuff. :)

**Comment by k0nsl** [comment]
Agreed. It'd be nice if `linx` would support `Minio` (self-hosted S3).
