### ISSUE TITLE
Display contents of tar.gz/tar.xz/zip

### ISSUE THREAD

**Issue by matthazinski** [andreimarcu/linx-server#34]

**Comment by andreimarcu** [comment]
https://golang.org/pkg/archive/tar/#example_
https://golang.org/pkg/archive/zip/#ReadCloser

**Comment by mutantmonkey** [comment]
https://en.wikipedia.org/wiki/Zip_bomb

**Comment by matthazinski** [comment]
Sure, but current linx supports it.

**Comment by andreimarcu** [comment]
I think it's not an issue, since we're not decompressing it but just reading filenames from the header.
