### ISSUE TITLE
basic HTTP server

### ISSUE THREAD

**Issue by quiznilo1** [andreimarcu/linx-server#64]
I can access a basic HTTP server instance from localhost, but not from remote.

'Firefox can't establish a connection to the server at testserver.host.funtoo.org:8080'.  Other remote clients report the same issue.

This is just running the basic built-in http server:
    cd $GOPATH/src/github.com/andreimarcu/linx-server
    ./linx-server

**Comment by andreimarcu** [comment]
Hi there,  what is your -bind argument? Are you binding to an external interface?

**Comment by quiznilo1** [comment]
I fixed it, from your question, it suddenly clicked, and I bound to a port, not an IP address/port, and it worked.

**Comment by andreimarcu** [comment]
Cool !  Using only a port in the bind is simply a shortcut for 0.0.0.0:port
