### ISSUE TITLE
Download with original name

### ISSUE THREAD

**Issue by rlex** [andreimarcu/linx-server#77]
Something like 

```
<a href="linx.instance/linx-hash" download="original_name.ext">get</a>
```

While original name of file you uploaded is stored in metadata can be a nice feature to have.

**Comment by andreimarcu** [comment]
Hi there, thought about it for a while but then it comes down to:
1. Not allowing custom filenames, everything is a hash and contains the original filename (a la zippyshare and co)
2. Not retaining the original filename allows for people to upload files without worrying about disclosing things you could infer from the filename

Now both of these could be dealt with using configuration settings and such, pull requests welcome !
