### ISSUE TITLE
Add option to force all uploads to have a randomized file name

### ISSUE THREAD

**Issue by theblazehen** [andreimarcu/linx-server#86]

**Comment by andreimarcu** [comment]
I had thought about it as well, however I'm still not sure what you would do about file extensions. Right now someone could upload a file "a.longernonrandomizedextension" and it would upload as "gf75ghf2h.longernonrandomizedextension".

At this point either you consider that's not an issue, or maybe have a list of approved extensions

**Comment by theblazehen** [comment]
@andreimarcu Well, have it work the same way as if I passed -r to linx-client, or ticked the box on the web client? I don't quite consider the non randomized extension an issue.

Or I'd be happy with a way to set always randomize filename in linx-client config file

**Comment by andreimarcu** [comment]
Yeah, that sounds good

**Comment by Malchemy** [comment]
Has this feature been implemented? Noticed this ticket's a few years old.

**Comment by andreimarcu** [comment]
@Malchemy It hasn't, feel free to do it
