### ISSUE TITLE
Web upload possible when using the authfile option

### ISSUE THREAD

**Issue by c0d1ng** [andreimarcu/linx-server#88]
When using the `authfile` option, the user can also upload via web if he entered the correct password to authenticate/login.

**Comment by andreimarcu** [comment]
This would be nice :)

**Comment by mutantmonkey** [comment]
Basic auth would probably work well for this. Support could be added for usernames, or it could just accept particular one or even any.

**Comment by fanningert** [comment]
You can set a basic auth on subpath `/upload` and `/paste`, when you us a webserver as proxy.
I am using caddy a proxy for linx, with basic auth on this two subpaths.

**Comment by sprnza** [comment]
Hi there! Is there any update on this? Or is there another way to use web upload when `authfile` is set?

**Comment by andreimarcu** [comment]
I don't think there's been any work going towards this issue, but feel free to take it!

**Comment by sprnza** [comment]
I've found a workaround. I set Linx-Api-Key header in my browser's requests.

**Comment by c0d1ng** [comment]
@sprnza how exactly did you do this?

**Comment by c0d1ng** [comment]
@sprnza I see, though I would still be interested in your code snippets, at least it's a start 😃

**Comment by sprnza** [comment]
@c0d1ng For Firefox there is an [extension](http://www.garethhunt.com/modifyheaders/) that allows to add custom headers. In Luakit add a web_module in rc.lua:
```
require_web_module("add_linx_apikey")
```
the module code:
```
local _M = {}

local function domain_from_uri(uri)
    local domain = (uri and string.match(string.lower(uri), "^%a+://([^/]*)/?"))
    -- Strip leading www. www2. etc
    domain = string.match(domain or "", "^www%d?%.(.+)") or domain
    return domain or ""
end

luakit.add_signal("page-created", function(page)
    page:add_signal("send-request", function(p, _, headers)
        if domain_from_uri(p.uri) == "paste.you_addres.url" then
            headers["Linx-Api-Key"] = "YOUR_IP_KEY"
            msg.verbose("Adding custom header")
        end
    end)
end)

```
