### ISSUE TITLE
All pastes are able to be edited by anyone

### ISSUE THREAD

**Issue by theblazehen** [andreimarcu/linx-server#89]
I did a paste from linx-client, and when I visited the paste via a web browser it gave me an edit option, and I could successfully edit it.

**Comment by andreimarcu** [comment]
The naming could probably be changed, but you're editing a **new** paste, you're not actually replacing the existing file. 

We could probably use **fork** instead

**Comment by theblazehen** [comment]
Okay. Thanks for the prompt response
