### ISSUE TITLE
Sharex config? 

### ISSUE THREAD

**Issue by formatme** [andreimarcu/linx-server#91]
Anyone use one? It would be nice to have one, i might make one.

**Comment by formatme** [comment]
I might just use sharex to take pic then upload with the uploader or make a config

**Comment by andreimarcu** [comment]
Here's how it should look:
```
{
  "Name": "your linx",
  "RequestType": "POST",
  "RequestURL": "https://your.linx.example/upload",
  "FileFormName": "file",
  "Headers": {
    "Linx-Randomize": "false"
  },
  "ResponseType": "RedirectionURL"
}
```

Chagne your.linx.example to match where your linx instance is. Also feel free to change Linx-Randomize to true if you want random filenames
