### ISSUE TITLE
Configurable maximum expiry value

### ISSUE THREAD

**Issue by noqqe** [andreimarcu/linx-server#99]
It would be nice if Linx would have a configurable maximum expiry value. 

```
-maxexpire 86400
```

Usecase: I dont want others to be able to upload files to my system which last there forever.

**Comment by andreimarcu** [comment]
Sounds like a good idea

**Comment by noqqe** [comment]
Btw: As a workaround I patched the upload.go to have a hardcoded expire, which is not very userfriendly.

https://gist.github.com/noqqe/190cf3949cc2cfae6fcd9b572cee9122

**Comment by andreimarcu** [comment]
@noqqe You can try it now
